FROM python:3.9-slim
WORKDIR /app

# ดึงไฟล์จากจุดนอกสุด
COPY requirements.txt . 

RUN pip install --no-cache-dir -r requirements.txt

# คัดลอกเฉพาะ Code ของ Service นั้นๆ เข้าไป
COPY service_b/ . 

# คอมไพล์ gRPC (ถ้ามีโฟลเดอร์ proto)
RUN if [ -d "proto" ]; then \
    python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. proto/user.proto; \
    fi

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]